### ISSUE TITLE
Unable to load plugin, loader not found. 

### ISSUE THREAD

**Issue by sapphic-wallflower** [ToppleKek/discord-rhythmbox-plugin#13]
![image](https://user-images.githubusercontent.com/70827619/134955775-5daf0960-5491-43fa-bc3a-0985a1c42e80.png)

```
** (rhythmbox:179888): WARNING **: 13:16:57.475: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (rhythmbox:179888): WARNING **: 13:16:57.476: Please check the installation of all the Python related packages required by libpeas and try again

(rhythmbox:179888): libpeas-WARNING **: 13:16:57.476: Loader 'python3' is not a valid PeasPluginLoader instance
```

Follow the instructions in the readme & verified I had python updated (Python3.9.7)

**Comment by ToppleKek** [comment]
Do you have pyGObject? You can install it with pip or if you are on Ubuntu it is in the repos `python3-gi`

**Comment by sapphic-wallflower** [comment]
`Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (3.38.0)`
`Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject) (1.16.2)`

I do have it installed, yeah.

**Comment by sapphic-wallflower** [comment]
I figured out the issue to my problem, I found the solution [in this thread.](https://askubuntu.com/questions/1265991/how-do-i-fix-the-plugin-external-tools-could-not-be-loaded-an-error-occured)
