### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by deadly-carp** [ToppleKek/discord-rhythmbox-plugin#19]
I installed pypresence and put the folder in my plugins but it doesn't work and show a little red icon.
![image](https://github.com/user-attachments/assets/dc6609d9-2f4c-4e17-8e39-d2a24e1f6d59)

**Comment by TheKevinGDX** [comment]
Same problem :(

![imagen](https://github.com/user-attachments/assets/16a3aceb-40c6-4900-ad13-4301e96238f7)

**Comment by deadly-carp** [comment]
I solved the problem, try to install pypresence via apt and if that doesn't work, remove the file that's called something like ...-WARNING from the python folder, it doesn't affect anything
