### ISSUE TITLE
The plugin doesn't work in Solus Budgie

### ISSUE THREAD

**Issue by Reiddragon** [ToppleKek/discord-rhythmbox-plugin#3]
the issue is just like this one https://github.com/ToppleKek/discord-rhythmbox-plugin/issues/2 so I suspect it's a Budgie thing. Whatever it is, however, it just refuses to load no matter what I do: I disabled every other plugin, I reinstalled pypresence, I reinstalled the plugin. Nothing works. So thanks for your time, and I hope you can fix it. Cheers.

**Comment by ToppleKek** [comment]
Sorry for the late response! I've just tried this in an Ubuntu Budgie VM and everything seems to work fine... Did you try pip3 over pip? Do you have discord open when you try to enable the plugin? Are you getting the exact same error as #2? Thanks!

**Comment by Reiddragon** [comment]
I really don't know what's happening here, but here's what I did:
I uninstalled `pypresence` using both pip2 and pip3, then I reinstalled it only with pip3, and now it works.
Really weird, if you ask me. Anyway, thanks for replying.
