### ISSUE TITLE
Plugin Activation Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by jdgwf** [ToppleKek/discord-rhythmbox-plugin#4]
Ubuntu 18.04.1 - rhythmbox 3.4.2

Python 3.6.5 (looks like Rhythmbox is calling this one)
Python 2.7.15rc1

Tried installing the plugin in both 
`/usr/lib/rhythmbox/plugins` (via sudo)
and
`~/.local/share/rhythmbox/plugins/`

Got this error when enabling the plugin via the menu (and grays out once fails) in both locations (plugin shows up and disappears when not installed):
![image](https://user-images.githubusercontent.com/316824/45508630-e57e4f00-b75a-11e8-80a8-bba2c1325e17.png)

**Comment by ToppleKek** [comment]
I plan on adding some easy ways to retry the connection to discord, but this error usually means you don't have discord running when you loaded the plugin/started rhythmbox. Try it again with discord running in the background. Like I said I will be adding something to make this easier in the future so hopefully you wont have to go through closing and opening it again and again.

**Comment by jdgwf** [comment]
I have discord running. I wonder if it's because it (discord) is installed via a snap. Let me research that.

**Comment by ToppleKek** [comment]
It could be because of that, you'd have to ask the author of pypresence about that. Have you tried the official .deb file from discord?

**Comment by jdgwf** [comment]
Not yet - looking through snap's interfaces to activate/deactivate 

https://docs.snapcraft.io/reference/interfaces

**Comment by ToppleKek** [comment]
Alright, let me know if you have any luck!

**Comment by jdgwf** [comment]
99.9% sure it's not you.
.deb install works beautifully.

FYI I added an issue in the discord snap: https://github.com/snapcrafters/discord/issues/42

Thanks for looking into it. If a solution is found I'll let you know so you can update the README :)

Thanks for all you do!
